version:	"3.7"
services:	
  nginx:
    build: ./mariadb
    command: command                                    # command after build container
    # image:					debian:buster                     # base image
    restart:				always                            # if need restart container for crash
    # container_name: nginx                               # container name
    ports:
      - 9000:9000
      - 443:443
    # environment:
    volumes:                                          # work directory
      - .
    networks:
      - host
  wordpress:
    build: ./nginx
    # image:					debian:buster                     # base image
    restart:				always                            # if need restart container for crash
    container_name: wordpress                           # container name
    # environment:
    ports:
      - 3306:3306
    volumes:                                          # work directory
      - .
    depends_on:                                         # wait start prev containers
      - nginx
  mariadb:
    build: ./wordpress
    # image:					debian:buster                     # base image
    restart:				always                            # if need restart container for crash
    container_name: mariadb                             # container name
    # environment:
    ports:
      - 3306:3306
    volumes:                                          # work directory
      - .
    depends_on:                                         # wait start prev containers
      - nginx
      - wordpress
