version:	'1' #???
services:	
	nginx:
		images:					debian:buster
		restart:				always
		container_name: nginx
		ports:
			- 9000:9000
			- 443:443
		environment:
	wordpress:
		images:					debian:buster
		restart:				always
		container_name: wordpress
		environment:
		ports:
			- 3306:3306
	mariadb:
		images:					debian:buster
		restart:				always
		container_name: mariadb
		environment:
		ports:
			- 3306:3306
